print N'@@LOCK_TIMEOUT:  ' + CAST(@@LOCK_TIMEOUT as nvarchar);


go


MERGE INTO dbo.TheTable
 AS TARGET
USING (VALUES ) AS SOURCE(Id, name, fun) ON [SOURCE].[Id] = [TARGET].[Id]
WHEN NOT MATCHED BY TARGET THEN INSERT (Id, name, fun) VALUES (SOURCE.Id, SOURCE.name, SOURCE.fun)
WHEN MATCHED AND (NULLIF (SOURCE.fun, TARGET.fun) IS NOT NULL
                  OR NULLIF (SOURCE.name, TARGET.name) IS NOT NULL
                  OR NULLIF (SOURCE.Id, TARGET.Id) IS NOT NULL) THEN UPDATE 
SET TARGET.Id   = SOURCE.Id,
    TARGET.name = SOURCE.name,
    TARGET.fun  = SOURCE.fun
WHEN NOT MATCHED BY SOURCE THEN DELETE;